/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StudentLoanRouteImport } from './routes/student-loan'
import { Route as InvestmentRouteImport } from './routes/investment'
import { Route as InterestRouteImport } from './routes/interest'
import { Route as HomeLoanRouteImport } from './routes/home-loan'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'

const StudentLoanRoute = StudentLoanRouteImport.update({
  id: '/student-loan',
  path: '/student-loan',
  getParentRoute: () => rootRouteImport,
} as any)
const InvestmentRoute = InvestmentRouteImport.update({
  id: '/investment',
  path: '/investment',
  getParentRoute: () => rootRouteImport,
} as any)
const InterestRoute = InterestRouteImport.update({
  id: '/interest',
  path: '/interest',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeLoanRoute = HomeLoanRouteImport.update({
  id: '/home-loan',
  path: '/home-loan',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/faq': typeof FaqRoute
  '/home-loan': typeof HomeLoanRoute
  '/interest': typeof InterestRoute
  '/investment': typeof InvestmentRoute
  '/student-loan': typeof StudentLoanRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/faq': typeof FaqRoute
  '/home-loan': typeof HomeLoanRoute
  '/interest': typeof InterestRoute
  '/investment': typeof InvestmentRoute
  '/student-loan': typeof StudentLoanRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/faq': typeof FaqRoute
  '/home-loan': typeof HomeLoanRoute
  '/interest': typeof InterestRoute
  '/investment': typeof InvestmentRoute
  '/student-loan': typeof StudentLoanRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/faq'
    | '/home-loan'
    | '/interest'
    | '/investment'
    | '/student-loan'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/faq'
    | '/home-loan'
    | '/interest'
    | '/investment'
    | '/student-loan'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/faq'
    | '/home-loan'
    | '/interest'
    | '/investment'
    | '/student-loan'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  FaqRoute: typeof FaqRoute
  HomeLoanRoute: typeof HomeLoanRoute
  InterestRoute: typeof InterestRoute
  InvestmentRoute: typeof InvestmentRoute
  StudentLoanRoute: typeof StudentLoanRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/student-loan': {
      id: '/student-loan'
      path: '/student-loan'
      fullPath: '/student-loan'
      preLoaderRoute: typeof StudentLoanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/investment': {
      id: '/investment'
      path: '/investment'
      fullPath: '/investment'
      preLoaderRoute: typeof InvestmentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/interest': {
      id: '/interest'
      path: '/interest'
      fullPath: '/interest'
      preLoaderRoute: typeof InterestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home-loan': {
      id: '/home-loan'
      path: '/home-loan'
      fullPath: '/home-loan'
      preLoaderRoute: typeof HomeLoanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  FaqRoute: FaqRoute,
  HomeLoanRoute: HomeLoanRoute,
  InterestRoute: InterestRoute,
  InvestmentRoute: InvestmentRoute,
  StudentLoanRoute: StudentLoanRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
